### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by degenaro** [OpenLiberty/sample.daytrader8#1]
[INFO] [ERROR   ] Error: displayQuote.jsp exception. Check that symbol: exists in the database.
[INFO] 	java.lang.NullPointerException

I'm attempting to deploy daytrader sample application and employ jmeter to exercise same, per jmeter_files/README.txt.  The daytrader app deploys fine, and I'm able to visit website.  After deploying jmeter and required JMeterWebSocketSamplers jar, I launch:

./jmeter -n -t /home/degenaro/trader/jmeter_files/daytrader8.jmx -JHOST=abbey-road.sl.cloud9.ibm.com -JPORT=9080 -JPROTOCOL=http -JMAXTHINKTIME=100 -JDURATION=300
Creating summariser <summary>
Created the tree successfully using /home/degenaro/trader/jmeter_files/daytrader8.jmx
Starting standalone test @ Mon Nov 18 07:53:35 CST 2019 (1574085215252)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +      1 in 00:00:01 =    1.5/s Avg:   410 Min:   410 Max:   410 Err:     0 (0.00%) Active: 30 Started: 30 Finished: 0
summary +    142 in 00:00:06 =   24.1/s Avg:  1643 Min:     7 Max:  3759 Err:     0 (0.00%) Active: 50 Started: 50 Finished: 0

And on the liberty console, I see NPE.

Perhaps this is user error, but it's not clear what I've done wrong.  Is application population step needed?  Is that documented?

**Comment by jdmcclur** [comment]
Hmm, You may need to set -JSTOCKS= (and probably -JTOPUID=) lower. On the config page you can see how many stocks and users are in the db. Set these values to stocks-1 (and users-1).
